// Employer_class = {
//     employers: [],
//     searchData: {
//     employer_id: "",
//     username: "",
//     company_name: "",
//     create_date: "",
//     email: "",
//     logo: "",
//     industry_name: "",
//     describle: "",
//     benefit: [],
//     work_location: "",
//     address: "",    
//     city_name: "",
//     scale: "",
//     // scale_min: "",
//     // scale_max: "",
//     employer_status: "",
//   },